
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-09
owner: ucsb-cs156-s26
repo_name: team01-s26-09
pull_requests: [{"author":{"id":"U_kgDODER-4g","is_bot":false,"login":"nathanqiuUCSB","name":"Nathan_Qiu"},"headRefName":"nq-RecommendationRequest-delete","number":58,"title":"Add DELETE endpoint for RecommendationRequest","url":"https://github.com/ucsb-cs156-s26/team01-s26-09/pull/58"},{"author":{"id":"U_kgDODER-4g","is_bot":false,"login":"nathanqiuUCSB","name":"Nathan_Qiu"},"headRefName":"nq-RecommendationRequest-put","number":57,"title":"Add PUT endpoint for RecommendationRequest","url":"https://github.com/ucsb-cs156-s26/team01-s26-09/pull/57"},{"author":{"id":"U_kgDODER-4g","is_bot":false,"login":"nathanqiuUCSB","name":"Nathan_Qiu"},"headRefName":"nq-RecommendationRequest-get-by-id","number":56,"title":"Add GET by id endpoint for RecommendationRequest","url":"https://github.com/ucsb-cs156-s26/team01-s26-09/pull/56"},{"author":{"id":"U_kgDODER-4g","is_bot":false,"login":"nathanqiuUCSB","name":"Nathan_Qiu"},"headRefName":"nq-RecommendationRequest-controller-getall-post","number":55,"title":"Add RecommendationRequest GET all and POST endpoints","url":"https://github.com/ucsb-cs156-s26/team01-s26-09/pull/55"},{"author":{"id":"U_kgDODER-4g","is_bot":false,"login":"nathanqiuUCSB","name":"Nathan_Qiu"},"headRefName":"nq-RecommendationRequest-create-db","number":54,"title":"Add RecommendationRequest table entity and migration","url":"https://github.com/ucsb-cs156-s26/team01-s26-09/pull/54"},{"author":{"id":"MDQ6VXNlcjY2MzMzMjQ0","is_bot":false,"login":"CooperDalton","name":"Cooper Dalton"},"headRefName":"cd-menuitemreview-put","number":49,"title":"cd - add MenuItemReview update endpoint","url":"https://github.com/ucsb-cs156-s26/team01-s26-09/pull/49"}]
